-- ═══════════════════════════════════════════════════════════════════════════
-- FEATURE #2: Lead Magnet Schema Migration
-- Initializes the complete lead generation magnet system
-- 
-- IDEMPOTENT: Safe to run multiple times (uses IF EXISTS / IF NOT EXISTS)
-- MANUAL EXECUTION: This migration is NOT auto-executed by Flyway/Liquibase
-- Production deployment requires manual controlled execution
-- 
-- PHASE: 1A (Database + Domain Foundation)
-- CONSTRAINTS CHANGED: Lead email uniqueness (GLOBAL → workspace-scoped)
-- BACKWARD COMPATIBILITY: All existing leads remain intact
-- ═══════════════════════════════════════════════════════════════════════════

-- ───────────────────────────────────────────────────────────────────────────
-- STEP 1: DISCOVERY QUERY - Find existing email uniqueness constraint
-- ───────────────────────────────────────────────────────────────────────────
-- Run this FIRST to discover the actual constraint name before removal:
-- SELECT constraint_name FROM information_schema.table_constraints
-- WHERE table_name = 'leads' AND constraint_type = 'UNIQUE';
--
-- Expected constraint names (common patterns):
-- - leads_email_key (auto-generated by Hibernate)
-- - email_unique (manual naming)
-- - leads_unique_email (manual naming)
--
-- DO NOT assume constraint name. Verify against your schema first.
-- ───────────────────────────────────────────────────────────────────────────

-- ───────────────────────────────────────────────────────────────────────────
-- STEP 2: PRE-MIGRATION VALIDATION
-- Check for existing duplicate emails (case-insensitive) within workspaces
-- If this query returns rows, migration will FAIL at constraint creation
-- ───────────────────────────────────────────────────────────────────────────
-- Run before migration to identify conflicts:
-- SELECT workspace_id, LOWER(TRIM(email)) as normalized_email, COUNT(*) as count, array_agg(id) as lead_ids
-- FROM leads
-- GROUP BY workspace_id, LOWER(TRIM(email))
-- HAVING COUNT(*) > 1
-- ORDER BY workspace_id, count DESC;
--
-- If results are found:
-- - DO NOT proceed with migration
-- - Manually review and deduplicate/merge leads
-- - Retry migration after resolution
-- ───────────────────────────────────────────────────────────────────────────

-- ═══════════════════════════════════════════════════════════════════════════
-- MIGRATION STEPS
-- ═══════════════════════════════════════════════════════════════════════════

BEGIN;

-- ───────────────────────────────────────────────────────────────────────────
-- 1. REMOVE GLOBAL EMAIL UNIQUENESS CONSTRAINT
-- ───────────────────────────────────────────────────────────────────────────
-- Drop the global unique constraint on leads.email
-- Find constraint name from discovery query above
-- 
-- If constraint name is different, manually edit this line:
DO $$ BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name = 'leads' AND constraint_name = 'leads_email_key'
        AND constraint_type = 'UNIQUE'
    ) THEN
        ALTER TABLE leads DROP CONSTRAINT leads_email_key;
        RAISE NOTICE 'Dropped existing global email unique constraint: leads_email_key';
    ELSE
        RAISE NOTICE 'Global email unique constraint not found (already removed or different name)';
    END IF;
END $$;

-- ───────────────────────────────────────────────────────────────────────────
-- 2. ADD WORKSPACE-SCOPED EMAIL UNIQUENESS CONSTRAINT
-- ───────────────────────────────────────────────────────────────────────────
-- Add composite unique constraint: (workspace_id, email)
-- This allows same email across different workspaces
-- Email values must match exactly (case-sensitive) for this constraint
-- Email normalization (lowercase) happens in application layer
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name = 'leads' AND constraint_name = 'leads_workspace_email_unique'
        AND constraint_type = 'UNIQUE'
    ) THEN
        ALTER TABLE leads ADD CONSTRAINT leads_workspace_email_unique UNIQUE (workspace_id, email);
        RAISE NOTICE 'Added composite unique constraint: leads_workspace_email_unique (workspace_id, email)';
    ELSE
        RAISE NOTICE 'Composite unique constraint already exists: leads_workspace_email_unique';
    END IF;
END $$;

-- ───────────────────────────────────────────────────────────────────────────
-- 3. ADD source_magnet_id COLUMN AND FOREIGN KEY
-- ───────────────────────────────────────────────────────────────────────────
-- Add FK to lead_magnets table (not yet created)
-- ON DELETE SET NULL: if magnet deleted, lead loses reference but remains
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'leads' AND column_name = 'source_magnet_id'
    ) THEN
        ALTER TABLE leads ADD COLUMN source_magnet_id BIGINT;
        RAISE NOTICE 'Added column: leads.source_magnet_id';
    ELSE
        RAISE NOTICE 'Column already exists: leads.source_magnet_id';
    END IF;
END $$;

-- ───────────────────────────────────────────────────────────────────────────
-- 4. CREATE lead_magnets TABLE
-- ───────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS lead_magnets (
    id BIGSERIAL PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    slug VARCHAR(100) NOT NULL,
    public_token VARCHAR(36) NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    
    CONSTRAINT fk_magnet_workspace FOREIGN KEY (workspace_id)
        REFERENCES workspaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_magnet_created_by FOREIGN KEY (created_by_id)
        REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT lead_magnets_workspace_slug_unique UNIQUE (workspace_id, slug)
);

-- ───────────────────────────────────────────────────────────────────────────
-- 5. CREATE lead_magnet_submissions TABLE
-- ───────────────────────────────────────────────────────────────────────────
-- Stores individual form submissions
-- customFields: JSONB for dynamic form data
-- sessionTokenHash: SHA-256 for session deduplication
CREATE TABLE IF NOT EXISTS lead_magnet_submissions (
    id BIGSERIAL PRIMARY KEY,
    lead_magnet_id BIGINT NOT NULL,
    lead_id BIGINT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    company VARCHAR(255),
    session_token_hash VARCHAR(64) NOT NULL,
    referrer TEXT,
    custom_fields JSONB DEFAULT '{}'::jsonb,
    submitted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    
    CONSTRAINT fk_submission_magnet FOREIGN KEY (lead_magnet_id)
        REFERENCES lead_magnets(id) ON DELETE CASCADE,
    CONSTRAINT fk_submission_lead FOREIGN KEY (lead_id)
        REFERENCES leads(id) ON DELETE SET NULL
);

-- ───────────────────────────────────────────────────────────────────────────
-- 6. CREATE lead_magnet_views TABLE
-- ───────────────────────────────────────────────────────────────────────────
-- Permanent analytics storage for pageviews
-- sessionTokenHash: SHA-256 for session tracking
CREATE TABLE IF NOT EXISTS lead_magnet_views (
    id BIGSERIAL PRIMARY KEY,
    lead_magnet_id BIGINT NOT NULL,
    session_token_hash VARCHAR(64) NOT NULL,
    referrer TEXT,
    viewed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    
    CONSTRAINT fk_view_magnet FOREIGN KEY (lead_magnet_id)
        REFERENCES lead_magnets(id) ON DELETE CASCADE
);

-- ───────────────────────────────────────────────────────────────────────────
-- 7. ADD FOREIGN KEY: leads.source_magnet_id → lead_magnets
-- ───────────────────────────────────────────────────────────────────────────
-- Completed after lead_magnets table created
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'fk_lead_source_magnet'
        AND table_name = 'leads'
        AND constraint_type = 'FOREIGN KEY'
    ) THEN
        ALTER TABLE leads ADD CONSTRAINT fk_lead_source_magnet
            FOREIGN KEY (source_magnet_id) REFERENCES lead_magnets(id) ON DELETE SET NULL;
        RAISE NOTICE 'Added foreign key: leads.fk_lead_source_magnet → lead_magnets';
    ELSE
        RAISE NOTICE 'Foreign key already exists: leads.fk_lead_source_magnet';
    END IF;
END $$;

-- ───────────────────────────────────────────────────────────────────────────
-- 8. CREATE INDEXES FOR PERFORMANCE
-- ───────────────────────────────────────────────────────────────────────────

-- Indexes for lead_magnets
CREATE INDEX IF NOT EXISTS idx_magnet_workspace_id ON lead_magnets (workspace_id);
CREATE INDEX IF NOT EXISTS idx_magnet_public_token ON lead_magnets (public_token);
CREATE INDEX IF NOT EXISTS idx_magnet_is_active ON lead_magnets (is_active);
CREATE INDEX IF NOT EXISTS idx_magnet_created_at ON lead_magnets (created_at);
CREATE INDEX IF NOT EXISTS idx_magnet_workspace_slug ON lead_magnets (workspace_id, slug);

-- Indexes for lead_magnet_submissions
CREATE INDEX IF NOT EXISTS idx_submission_magnet_id ON lead_magnet_submissions (lead_magnet_id);
CREATE INDEX IF NOT EXISTS idx_submission_lead_id ON lead_magnet_submissions (lead_id);
CREATE INDEX IF NOT EXISTS idx_submission_session_token ON lead_magnet_submissions (session_token_hash);
CREATE INDEX IF NOT EXISTS idx_submission_magnet_email ON lead_magnet_submissions (lead_magnet_id, email);
CREATE INDEX IF NOT EXISTS idx_submission_submitted_at ON lead_magnet_submissions (submitted_at);
CREATE INDEX IF NOT EXISTS idx_submission_magnet_submitted ON lead_magnet_submissions (lead_magnet_id, submitted_at);

-- Indexes for lead_magnet_views
CREATE INDEX IF NOT EXISTS idx_view_magnet_id ON lead_magnet_views (lead_magnet_id);
CREATE INDEX IF NOT EXISTS idx_view_session_token ON lead_magnet_views (session_token_hash);
CREATE INDEX IF NOT EXISTS idx_view_viewed_at ON lead_magnet_views (viewed_at);
CREATE INDEX IF NOT EXISTS idx_view_magnet_viewed ON lead_magnet_views (lead_magnet_id, viewed_at);
CREATE INDEX IF NOT EXISTS idx_view_session_viewed ON lead_magnet_views (session_token_hash, viewed_at);

-- Indexes for leads updates
CREATE INDEX IF NOT EXISTS idx_lead_source_magnet_id ON leads (source_magnet_id);

-- ───────────────────────────────────────────────────────────────────────────
-- 9. VERIFY MIGRATION COMPLETION
-- ───────────────────────────────────────────────────────────────────────────
DO $$ 
DECLARE
    leads_exists INT;
    magnets_exists INT;
    submissions_exists INT;
    views_exists INT;
    composite_constraint_exists INT;
    global_constraint_exists INT;
BEGIN
    SELECT COUNT(*) INTO leads_exists FROM information_schema.tables WHERE table_name = 'leads';
    SELECT COUNT(*) INTO magnets_exists FROM information_schema.tables WHERE table_name = 'lead_magnets';
    SELECT COUNT(*) INTO submissions_exists FROM information_schema.tables WHERE table_name = 'lead_magnet_submissions';
    SELECT COUNT(*) INTO views_exists FROM information_schema.tables WHERE table_name = 'lead_magnet_views';
    
    SELECT COUNT(*) INTO composite_constraint_exists
    FROM information_schema.table_constraints
    WHERE table_name = 'leads' AND constraint_name = 'leads_workspace_email_unique'
    AND constraint_type = 'UNIQUE';
    
    SELECT COUNT(*) INTO global_constraint_exists
    FROM information_schema.table_constraints
    WHERE table_name = 'leads' AND constraint_name = 'leads_email_key'
    AND constraint_type = 'UNIQUE';
    
    RAISE NOTICE '════════════════════════════════════════════════════════════';
    RAISE NOTICE 'MIGRATION VERIFICATION REPORT';
    RAISE NOTICE '════════════════════════════════════════════════════════════';
    RAISE NOTICE 'leads table exists: %', CASE WHEN leads_exists > 0 THEN 'YES' ELSE 'NO' END;
    RAISE NOTICE 'lead_magnets table exists: %', CASE WHEN magnets_exists > 0 THEN 'YES' ELSE 'NO' END;
    RAISE NOTICE 'lead_magnet_submissions table exists: %', CASE WHEN submissions_exists > 0 THEN 'YES' ELSE 'NO' END;
    RAISE NOTICE 'lead_magnet_views table exists: %', CASE WHEN views_exists > 0 THEN 'YES' ELSE 'NO' END;
    RAISE NOTICE 'Composite unique constraint (workspace, email) exists: %', CASE WHEN composite_constraint_exists > 0 THEN 'YES' ELSE 'NO' END;
    RAISE NOTICE 'Global email unique constraint removed: %', CASE WHEN global_constraint_exists = 0 THEN 'YES' ELSE 'NO (check manually)' END;
    RAISE NOTICE '════════════════════════════════════════════════════════════';
    
    IF magnets_exists = 0 THEN
        RAISE EXCEPTION 'MIGRATION FAILED: lead_magnets table not created';
    END IF;
    IF submissions_exists = 0 THEN
        RAISE EXCEPTION 'MIGRATION FAILED: lead_magnet_submissions table not created';
    END IF;
    IF views_exists = 0 THEN
        RAISE EXCEPTION 'MIGRATION FAILED: lead_magnet_views table not created';
    END IF;
    IF composite_constraint_exists = 0 THEN
        RAISE EXCEPTION 'MIGRATION FAILED: composite unique constraint not created';
    END IF;
    
    RAISE NOTICE 'MIGRATION COMPLETED SUCCESSFULLY ✓';
END $$;

COMMIT;

-- ═══════════════════════════════════════════════════════════════════════════
-- MIGRATION COMPLETE
-- ═══════════════════════════════════════════════════════════════════════════
-- 
-- WHAT CHANGED:
-- ✓ Removed global unique constraint on leads.email
-- ✓ Added UNIQUE(workspace_id, email) composite constraint
-- ✓ Added leads.source_magnet_id FK column
-- ✓ Created lead_magnets table (magnet definitions)
-- ✓ Created lead_magnet_submissions table (form submissions + JSONB)
-- ✓ Created lead_magnet_views table (pageview analytics)
-- ✓ Created all required indexes for performance
-- 
-- BACKWARD COMPATIBILITY:
-- ✓ All existing leads remain intact
-- ✓ Feature #1 conversion fields untouched (converted, converted_at, etc.)
-- ✓ No data loss or lead deletion
-- 
-- NEXT STEPS:
-- 1. Deploy application code (entities, repositories, services)
-- 2. Run mvn clean compile -DskipTests to verify compilation
-- 3. Test Lead creation/update with email normalization
-- 4. Test feature #2 magnet submission flow (Phase 1B)
-- 
-- ROLLBACK INSTRUCTIONS (if needed):
-- - Drop foreign key: ALTER TABLE leads DROP CONSTRAINT fk_lead_source_magnet;
-- - Drop new tables: DROP TABLE lead_magnet_views; DROP TABLE lead_magnet_submissions; DROP TABLE lead_magnets;
-- - Drop composite constraint: ALTER TABLE leads DROP CONSTRAINT leads_workspace_email_unique;
-- - Re-add global constraint: ALTER TABLE leads ADD CONSTRAINT leads_email_key UNIQUE (email);
-- - Drop source_magnet_id column: ALTER TABLE leads DROP COLUMN source_magnet_id;
-- ═══════════════════════════════════════════════════════════════════════════
