import { Edit2, Eye, MoreVertical, Send, Trash2 } from 'lucide-react'
import { format } from 'date-fns'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import CampaignStatusBadge from './CampaignStatusBadge'

export default function EmailCampaignTable({ campaigns, canManage, onEdit, onDelete, onSend }) {
  const [openId, setOpenId] = useState(null)
  const date = (value) => value ? format(new Date(value), 'MMM dd, yyyy') : '-'
  return <div className="overflow-x-auto"><table className="w-full"><thead><tr className="border-b border-gray-200 dark:border-[#30363D]">{['Campaign', 'Subject', 'Status', 'Recipients', 'Scheduled', 'Created', 'Actions'].map((label) => <th key={label} className="px-4 py-3 text-left text-xs font-semibold text-gray-700 dark:text-gray-300">{label}</th>)}</tr></thead><tbody>{campaigns.map((campaign) => <tr key={campaign.id} className="border-b border-gray-100 transition-colors hover:bg-gray-50 dark:border-[#21262D] dark:hover:bg-[#0D1117]"><td className="px-4 py-3 text-sm font-medium text-gray-900 dark:text-white">{campaign.name}</td><td className="max-w-56 truncate px-4 py-3 text-sm text-gray-600 dark:text-gray-400">{campaign.subject}</td><td className="px-4 py-3"><CampaignStatusBadge status={campaign.status} /></td><td className="px-4 py-3 text-sm text-gray-600 dark:text-gray-400">{campaign.totalRecipients || 0}</td><td className="px-4 py-3 text-sm text-gray-600 dark:text-gray-400">{date(campaign.scheduledAt)}</td><td className="px-4 py-3 text-sm text-gray-600 dark:text-gray-400">{date(campaign.createdAt)}</td><td className="px-4 py-3"><div className="relative"><button type="button" aria-label={`Actions for ${campaign.name}`} onClick={() => setOpenId(openId === campaign.id ? null : campaign.id)} className="rounded p-1 hover:bg-gray-200 dark:hover:bg-[#30363D]"><MoreVertical size={16} /></button>{openId === campaign.id && <div className="absolute right-0 z-30 mt-1 w-44 rounded-lg border border-gray-200 bg-white shadow-lg dark:border-[#30363D] dark:bg-[#161B22]"><Link to={`/marketing/email-campaigns/${campaign.id}`} onClick={() => setOpenId(null)} className="flex w-full items-center gap-2 px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-[#21262D]"><Eye size={14} />View details</Link>{canManage && campaign.status === 'DRAFT' && <button type="button" onClick={() => { onEdit(campaign); setOpenId(null) }} className="flex w-full items-center gap-2 px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-[#21262D]"><Edit2 size={14} />Edit</button>}{canManage && ['DRAFT', 'SCHEDULED'].includes(campaign.status) && <button type="button" onClick={() => { onSend(campaign); setOpenId(null) }} className="flex w-full items-center gap-2 px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-[#21262D]"><Send size={14} />Send now</button>}{canManage && <button type="button" onClick={() => { onDelete(campaign); setOpenId(null) }} className="flex w-full items-center gap-2 px-4 py-2 text-sm text-red-700 hover:bg-red-50 dark:text-red-400 dark:hover:bg-red-900/20"><Trash2 size={14} />Delete</button>}</div>}</div></td></tr>)}</tbody></table></div>
}
